import type { RegistryResult } from "./registry-types.ts";

const HEADER = `// AUTO-GENERATED by @cloud/platform-config — DO NOT EDIT BY HAND.\n// Regenerate via the codegen script; manual edits are overwritten and fail CI.\n`;
const q = (s: string): string => JSON.stringify(s);

function emitUnion(name: string, codes: readonly string[]): string {
  if (codes.length === 0) return `export type ${name} = never;\n`;
  return `export type ${name} =\n${codes.map((c) => `  | ${q(c)}`).join("\n")};\n`;
}

export function emitRegistry(args: {
  result: RegistryResult;
  contractScope: Record<string, string[]>;
  i18n: Record<string, unknown>;
  contractTypes: readonly string[];
}): Record<string, string> {
  const { result, contractScope, i18n } = args;
  const files: Record<string, string> = {};

  files["registry-types.generated.ts"] =
    HEADER + "\n" + emitUnion("PermissionCode", result.permissionCodeUnion) + "\n" + emitUnion("MenuCode", result.menuCodeUnion);

  files["permission-registry.generated.ts"] =
    HEADER +
    '\nimport type { PermissionCode, MenuCode } from "./registry-types.generated.ts";\n\n' +
    "export interface GeneratedPermissionEntry { code: PermissionCode; belongToMenuCode: MenuCode; label: string; desc: string; deprecated: boolean; }\n\n" +
    "export const PERMISSION_REGISTRY: Record<PermissionCode, GeneratedPermissionEntry> = " +
    JSON.stringify(result.permissionRegistry, null, 2) +
    " as Record<PermissionCode, GeneratedPermissionEntry>;\n\n" +
    "export function codeToMenu(code: string): MenuCode | null {\n" +
    "  return (PERMISSION_REGISTRY as Record<string, GeneratedPermissionEntry | undefined>)[code]?.belongToMenuCode ?? null;\n}\n";

  files["menu-registry.generated.ts"] =
    HEADER +
    '\nimport type { MenuCode } from "./registry-types.generated.ts";\n\n' +
    "export interface GeneratedMenuEntry { menuCode: MenuCode; title: string; parentMenuCode: MenuCode | null; path: string | null; icon: string | null; order: number; }\n\n" +
    "export const MENU_REGISTRY: Record<MenuCode, GeneratedMenuEntry> = " +
    JSON.stringify(result.menuRegistry, null, 2) +
    " as Record<MenuCode, GeneratedMenuEntry>;\n";

  files["contract-scope.generated.ts"] =
    HEADER +
    '\nimport type { PermissionCode } from "./registry-types.generated.ts";\n' +
    'import type { ContractType } from "../../catalog/contract-types.ts";\n\n' +
    "export const CONTRACT_SCOPE: Record<ContractType, PermissionCode[]> = " +
    JSON.stringify(contractScope, null, 2) +
    " as Record<ContractType, PermissionCode[]>;\n";

  files["i18n/en.json"] = JSON.stringify(i18n, null, 2) + "\n";

  return files;
}
